- .github/workflows/checks.yaml
- config/settings.py
> 📝ci modify

- .github/workflows/checks.yaml
- config/settings.py
- poetry.lock
- pyproject.toml
> 📝 update ci

- .gitignore
> :memo: update gitignore

- Accounts/admin.py
- Accounts/apps.py
- Accounts/models.py
- Accounts/tests.py
- Accounts/views.py
- Idols/admin.py
- Idols/apps.py
- Idols/models.py
- Idols/tests.py
- Idols/views.py
- Preferences/admin.py
- Preferences/apps.py
- Preferences/models.py
- Preferences/tests.py
- Preferences/views.py
- Schedules/admin.py
- Schedules/apps.py
- Schedules/models.py
- Schedules/tests.py
- Schedules/views.py
> :memo: create apps

- .github/workflows/checks.yaml
- Accounts/admin.py
- Accounts/models.py
- Accounts/tests.py
유저 모델 테스트, 유저 어드민 페이지를 추가하였고 유저 모델을 수정하였습니다
> ✨ test user model and update user and add user admin page

- Schedules/tests.py
> ✨ test schedule model

- Accounts/serializers.py
- Accounts/urls.py
- Accounts/views.py
- config/settings.py
- config/urls.py
- poetry.lock
- pyproject.toml
> ✨ create login api

- config/settings.py
> 🐛 fix settings

- config/settings.py
- poetry.lock
- pyproject.toml
> ✨ add gunicorn

- Accounts/views.py
- config/settings.py
- config/urls.py
> ✨ set swagger

- .github/workflows/checks.yaml
- Accounts/serializers.py
- Accounts/urls.py
- Accounts/views.py
- config/settings.py
- config/urls.py
- poetry.lock
- pyproject.toml
> ✨ create social login api

- Accounts/serializers.py
- Accounts/urls.py
- Accounts/views.py
- config/settings.py
> ✨ create logout view

- .github/workflows/checks.yaml
- Accounts/serializers.py
- Accounts/urls.py
- Accounts/views.py
- config/settings.py
- templates/email_verification.html
> ✨ create register and mail verify vpi

- Accounts/views.py
> 📝 update account/views.py

- Accounts/serializers.py
- Accounts/urls.py
- Accounts/views.py
> ✨ create find_email api

- .github/workflows/checks.yaml
- config/settings.py
- poetry.lock
- pyproject.toml
> 📝 update dotenv

- Accounts/views.py
> 📝 update account/views's response

- Accounts/serializers.py
- Accounts/services.py
- Accounts/urls.py
- Accounts/views.py
- poetry.lock
- pyproject.toml
어카운트 앱에 그동안 작성했었던 코드의 전반적인 리팩토링을 진행.
로그인, 소셜로그인, 회원가입, 로그아웃, 이메일 인증, 이메일 찾기, 비밀번호 찾기, 비밀번호 리셋 기능을 포함.
뷰는 제네릭으로 변경.
시리얼라이저에서 비즈니스 로직을 서비스로 분리.
> 250321 Accounts앱의 코드 리팩토링

- Accounts/serializers.py
- Accounts/urls.py
- Accounts/views.py
로그인한 사용자가 자신의 정보를 확인.
액세스 토큰을 받아서 인증을 받고 정보를 리턴.
> 250321 자신의 정보를 조회하는 기능 구현

- Accounts/serializers.py
- Accounts/services.py
- Accounts/urls.py
- Accounts/views.py
로그인한 사용자의 액세스 토큰으로 인증을 받아서 정보를 수정하는 기능.
닉네임, 전화번호, 비밀번호 변경 가능.
partial=False로 일부 정보만 변경가능(patch).
> 250321 유저정보수정 기능 구현

- config/settings.py
> 📝 update settings

- Accounts/serializers.py
- Accounts/urls.py
- Accounts/views.py
이메일/닉네임/전화번호중 하나를 타입으로 받고 밸류로 값을 받아서 중복체크 시도.
중복이 없을시 값을 그대로 리턴.
중복이 있을시 에러 발생.
> 250321 이메일/닉네임/전화번호 중복체크기능 구현

- Accounts/views.py
리턴을 custom_response 함수로 만들어서 처리.
로직을 perform_create로 분리해서 처리.
> 250324 Accounts앱의 코드 2번째 리팩토링

- Idols/admin.py
- Preferences/serializers.py
- Preferences/services.py
- Preferences/urls.py
- Preferences/views.py
- config/settings.py
- config/urls.py
그룹 구독, 알림 기능 ON/OFF, 그룹 구독 해제, 구독한 그룹 보는 기능 구현.
> 250326 구독 API 구현

- config/settings.py
> 250326 디버그 파일 생성

- Accounts/services.py
- Preferences/notification_service.py
- Schedules/views.py
- config/settings.py
스케줄이 등록되면 해당 그룹을 구독중인 유저에게 메일 알림 전송.
스레드풀을 이용해 구현.
smtp를 네이버에서 mailjet으로 변경(하루 200통 무료).
> 250326 이메일 알림 기능 구현 및 smtp 변경

- config/settings.py
> 250326 SMTP 변경

- Accounts/views.py
> 250327 어카운트 앱의 스웨거 일부 추가

- Idols/views.py
아이돌 앱 내의 소속사/그룹/아이돌 항목에 대한 스웨거를 작성했습니다.
> 250327 아이돌 스웨거 작성

- Idols/views.py
아이돌, 그룹, 에이전시 생성/수정 시 이미지 업로드 가능하도록 수정.
> 250327 스웨거에 이미지 업로드 기능 추가

- Accounts/serializers.py
> 250327 유저 정보에 추가 정보

- Idols/views.py
- config/base_exception.py
- config/logging.py
- config/settings.py
- config/urls.py
- tests/test_views.py
Custom exception 설정을 위해 base_exception을 추가했습니다
debug = False 상태에서 확인되어야 하기 때문에 overriding method 사용하여 설정해주었습니다.
raise exception 확인을 위해 test 코드를 추가했습니다. (tests폴더 내)
exception 설정을 위해 Logging에도 exception handler를 추가해두었습니다
> 250330 오류 처리 코드 추가

- Schedules/urls.py
- Schedules/views.py
- poetry.lock
- pyproject.toml
-------
엑셀 파일 연동 및 이용을 위해 openpyxl을 사용했습니다.
load_workbook을 이용하여 엑셀 파일을 열어 볼 수 있습니다
그룹과 참여 멤버는 아이디값을 받기 때문에 정수로 받을 수 있는 로직을 추가했습니다.
(다만 엑셀에서 텍스트로 서식을 변환해주어야 합니다... 자동 인식은 오류가 납니다.)
단점은... 엑셀 양식이 정해져 있다는 건데 문제가 될 것 같진 않고, 이름으로 등록 가능하게 변경해야할 것 같긴 합니다.
> 250401 엑셀 파일 업로드로 일정 대량 업로드 기능을 구현했습니다.

- Idols/urls.py
넣은 적이 없는데 ilog/idol은 왜 또 들어가 있던것이냐...
thanks to 대 철민님...
> 250402 url 패턴에 오류가 발견되어 수정했습니다.

- config/base_exception.py
base_exception에서 404에러 예외처리 진행했습니다
> 250402 404 에러 예외처리

- celery_app.py
- config/__init__.py
순환 에러를 발생시키는 장고셋업 제거.
__init__ 내용 되롤림.
> 250402 샐러리 워커 관련 에러 수정

- Idols/views.py
- config/permissions.py
슈퍼 유저 권한 요구 삭제. 
스태프 권한이 아닌 어드민 권한 요구하도록 변경.
> 250402 권한 관련 수정

- Idols/serializers.py
- Idols/views.py
소속사, 그룹, 아이돌의 중복 검사에서 자기 자신을 제외하는 로직을 추가하였습니다
> 250403 중복 검사 수정

- README.md
> 250403 readme 수정

- .github/workflows/checks.yaml
- Idols/views.py
- config/urls.py
- poetry.lock
> 250403 불필요 코드 삭제
